### ISSUE TITLE
Investigate options for Ready-To-Use React Components

### ISSUE THREAD

**Issue by mighty-mhsl** [fakng-agrgtr/fakng-ui#3]
MUI
https://mui.com/

Ant Design
https://ant.design/

Chakra UI
https://chakra-ui.com/

**Comment by qweered** [comment]
Comparison with mui and antd
https://chakra-ui.com/getting-started/comparison

**Comment by qweered** [comment]
Also https://npmtrends.com/@chakra-ui/utils-vs-@material-ui/system-vs-antd
Chakra-ui seems to rising, while others stagnate

**Comment by mighty-mhsl** [comment]
Will check all options today... :)

**Comment by mighty-mhsl** [comment]
Let's use MUI: https://mui.com/
