### ISSUE TITLE
Create basic MockUp for UI search page

### ISSUE THREAD

**Issue by mighty-mhsl** [fakng-agrgtr/fakng-ui#6]

**Comment by aitmamatovmusa** [comment]
**Pages**

![Image](https://user-images.githubusercontent.com/63698936/184501408-ab51dcd2-95bc-4064-a400-e81ed086d4ef.jpg)


![Image](https://user-images.githubusercontent.com/63698936/184501416-306e2ad9-8f5c-42e7-a616-88df8e48fe20.jpg)

**Comment by ibotlold** [comment]
if we remove the home page, the user will have fewer clicks to get information
as well development will focus only careers page
What thoughts?

**Comment by mighty-mhsl** [comment]
I think this is reasonable. Let's keep the home page for now because it's pretty small. Probably it'll be useful later. If no, we'll just update it to display vacancies list right away
